spring:
  application:
    name: api-auto-test
  profiles:
    active: uat
  datasource:
    url: jdbc:postgresql://localhost:5432/autotest
    username: admin
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8080

mybatis:
  mapper-locations: classpath*:mappers/**/*.xml
  type-aliases-package: com.api.model
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  level:
    com.api.mapper: DEBUG

# 自定义数据库配置
ehapi:
  lif:
    uat:
      driver: org.postgresql.Driver
      url: jdbc:postgresql://localhost:5432/autotest
      username: admin
      password: password
    dev:
      driver: org.postgresql.Driver
      url: jdbc:postgresql://localhost:5432/autotest_dev
      username: dev_user
      password: dev_password
    prod:
      driver: org.postgresql.Driver
      url: jdbc:postgresql://localhost:5432/autotest_prod
      username: prod_user
      password: prod_password

# 测试配置
test:
  timeout: 30000
  retry-count: 3
  parallel-threads: 5 