spring:
  application:
    name: api-auto-test
  profiles:
    active: uat

# Expected database configuration format for SessionFactory
ehapi:
  db:
    lif:
      uat:
        driver: org.postgresql.Driver
        url: jdbc:postgresql://localhost:5432/autotest
        username: admin
        password: password
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8080

mybatis:
  mapper-locations: classpath*:mappers/**/*.xml
  type-aliases-package: com.api.model
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  level:
    com.api.mapper: DEBUG
    com.api.helpers.SessionFactory: DEBUG
    org.apache.ibatis: DEBUG


# Test configuration
test:
  timeout: 30000
  retry-count: 3
  parallel-threads: 5

management:
  endpoint:
    health:
      show-details: always
  health:
    defaults:
      enabled: false
springdoc:
  api-docs:
    path: /v3/api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui/index.html
    enabled: true
    url: /openapi.yaml
    disable-swagger-default-url: true